# Generated by Django 5.0.6 on 2024-11-28 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='telegramprofile',
            table='user',
        ),
    ]
