# Generated by Django 5.0.6 on 2024-11-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_telegramprofile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='telegramprofile',
            table=None,
        ),
    ]
