# Generated by Django 5.0.6 on 2024-11-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_telegramprofile_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requiredchannels',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
