# Generated by Django 5.0.6 on 2024-11-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_code_updated_at_alter_language_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default='2024-11-23 23:43'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='language',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default='2024-11-23 23:43'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requiredchannels',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default='2024-11-23 23:43'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default='2024-11-23 23:43'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='text',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default='2024-11-23 23:43'),
            preserve_default=False,
        ),
    ]
