# Generated by Django 5.0.6 on 2024-12-03 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_code_updated_at_alter_language_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='common.telegramprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
