# Generated by Django 5.0.6 on 2024-12-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='title',
            field=models.TextField(),
        ),
    ]
